### ISSUE TITLE
[FEATURE] Make announcement bar static

### ISSUE THREAD

**Issue by cnu1812** [cnu1812/Community-Library#7]
### Description

It would be great if we made our announcement bar static.

**Comment by BhaveshAnandpara** [comment]
@cnu1812 Isn't Announcement Bar already Static ?

**Comment by cnu1812** [comment]
when you click close for the announcement bar, it will never appear to you again. so have to change that.

**Comment by BhaveshAnandpara** [comment]
@cnu1812  So basically as website reload it should appear again

**Comment by cnu1812** [comment]
Yes
