### ISSUE TITLE
[FEATURE] Edit Socials

### ISSUE THREAD

**Issue by cnu1812** [cnu1812/Community-Library#8]
### Description

Add stackup social links in footer

**Comment by BhaveshAnandpara** [comment]
Hey @cnu1812 I am Interested in working on this Issue Is this Still Open ??

**Comment by cnu1812** [comment]
@BhaveshAnandpara you can take up this issue. Add stackup socials.

**Comment by BhaveshAnandpara** [comment]
@cnu1812  Links for Socials?

**Comment by cnu1812** [comment]
> @cnu1812 Do I also need to include ( you may use .....) Sentence in Footer

No, need.

**Comment by BhaveshAnandpara** [comment]
@cnu1812 
![Screenshot 2022-07-20 194123](https://user-images.githubusercontent.com/87887912/180003961-88e59c6a-8b42-4720-9bee-a6be42ca84a4.png)


Is it ok ??

**Comment by BhaveshAnandpara** [comment]
@cnu1812 Consider it done ✅ should I do a PR ?

**Comment by cnu1812** [comment]
😊 sure
